name: 'localsend_rs'
version: '1.0.0+1'
publish_to: none
environment: 
  sdk: '>=3.2.0 <4.0.0'
description: A Rust Implementation of LocalSend protocl v2 for better performance
dependencies: 
  animations: ^2.0.11
  cupertino_icons: '^1.0.2'
  chinese_font_library: ^1.2.0
  device_info_plus: '^10.1.0'
  dio: '^5.4.0'
  equatable: '^2.0.5'
  file_picker: ^8.0.6
  filesize: ^2.0.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_riverpod: '^2.4.9'
  flutter_rust_bridge: 2.5.0
  freezed_annotation: '^2.4.2'
  logger: '^2.3.0'
  path_provider: '^2.1.1'
  riverpod_annotation: '^2.3.3'
  rust_builder: 
    path: 'rust_builder'
  shared_preferences: '^2.2.2'
  slang: '^3.31.0'
  slang_flutter: '^3.31.0'
  uuid: '^4.4.0'
  window_manager: ^0.4.2
  simple_icons: ^10.1.3
  desktop_drop: ^0.5.0
dev_dependencies: 
  build_runner: '^2.4.8'
  custom_lint: '^0.6.4'
  ffigen: ^14.0.1
  flutter_launcher_icons: ^0.14.0
  flutter_lints: '^4.0.0'
  flutter_test: 
    sdk: flutter
  freezed: '^2.4.6'
  innosetup: '^0.1.3'
  integration_test: 
    sdk: flutter
  pubspec_dependency_sorter: '^1.0.5'
  riverpod_generator: '^2.3.9'
  riverpod_lint: '^2.3.7'
  slang_build_runner: '^3.31.0'
  version: any
flutter: 
  uses-material-design: true
  assets: 
    - assets/icon/
