// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../api/model.dart';
import '../../frb_generated.dart';
import '../model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PendingMissionDto {
  final Mission? mission;
  final MissionState state;

  const PendingMissionDto({
    this.mission,
    required this.state,
  });

  @override
  int get hashCode => mission.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingMissionDto &&
          runtimeType == other.runtimeType &&
          mission == other.mission &&
          state == other.state;
}
