// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/model.dart';
import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mission.freezed.dart';

@freezed
sealed class FileState with _$FileState {
  const FileState._();

  const factory FileState.pending() = FileState_Pending;
  const factory FileState.transfer() = FileState_Transfer;
  const factory FileState.finish() = FileState_Finish;
  const factory FileState.skip() = FileState_Skip;
  const factory FileState.fail({
    required String msg,
  }) = FileState_Fail;
}

class MissionFileInfo {
  final FileInfo info;
  final FileState state;

  const MissionFileInfo({
    required this.info,
    required this.state,
  });

  @override
  int get hashCode => info.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MissionFileInfo &&
          runtimeType == other.runtimeType &&
          info == other.info &&
          state == other.state;
}

class MissionInfo {
  final String id;
  final NodeDevice sender;
  final List<MissionFileInfo> files;
  final MissionState state;

  const MissionInfo({
    required this.id,
    required this.sender,
    required this.files,
    required this.state,
  });

  @override
  int get hashCode =>
      id.hashCode ^ sender.hashCode ^ files.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MissionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          files == other.files &&
          state == other.state;
}
