// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/model.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'model.freezed.dart';

@freezed
sealed class FileState with _$FileState {
  const FileState._();

  const factory FileState.pending() = FileState_Pending;
  const factory FileState.transfer() = FileState_Transfer;
  const factory FileState.finish() = FileState_Finish;
  const factory FileState.skip() = FileState_Skip;
  const factory FileState.fail({
    required String msg,
  }) = FileState_Fail;
}

class MissionFileInfo {
  final FileInfo info;
  final FileState state;

  const MissionFileInfo({
    required this.info,
    required this.state,
  });

  @override
  int get hashCode => info.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MissionFileInfo &&
          runtimeType == other.runtimeType &&
          info == other.info &&
          state == other.state;
}

/// NOTE: variant order is the FRB wire index; do not reorder.
enum MissionState {
  idle,
  pending,
  transfering,
  finished,
  failed,
  canceled,
  busy,
  ;
}

class NodeDevice {
  final String alias;
  final String version;
  final String deviceModel;
  final String deviceType;
  final String fingerprint;
  final String address;
  final int port;
  final String protocol;
  final bool download;
  final bool announcement;
  final bool announce;

  const NodeDevice({
    required this.alias,
    required this.version,
    required this.deviceModel,
    required this.deviceType,
    required this.fingerprint,
    required this.address,
    required this.port,
    required this.protocol,
    required this.download,
    required this.announcement,
    required this.announce,
  });

  @override
  int get hashCode =>
      alias.hashCode ^
      version.hashCode ^
      deviceModel.hashCode ^
      deviceType.hashCode ^
      fingerprint.hashCode ^
      address.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      download.hashCode ^
      announcement.hashCode ^
      announce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeDevice &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          version == other.version &&
          deviceModel == other.deviceModel &&
          deviceType == other.deviceType &&
          fingerprint == other.fingerprint &&
          address == other.address &&
          port == other.port &&
          protocol == other.protocol &&
          download == other.download &&
          announcement == other.announcement &&
          announce == other.announce;
}

/// NOTE: variant order is the FRB wire index; do not reorder.
enum SessionDirection {
  send,
  receive,
  ;
}

@freezed
sealed class SessionEvent with _$SessionEvent {
  const SessionEvent._();

  /// Overall session state changed.
  const factory SessionEvent.stateChanged(
    MissionState field0,
  ) = SessionEvent_StateChanged;

  /// State of one file changed.
  const factory SessionEvent.fileStateChanged({
    required String fileId,
    required FileState state,
  }) = SessionEvent_FileStateChanged;

  /// Bytes transferred so far for one file.
  const factory SessionEvent.progress({
    required String fileId,
    required PlatformInt64 bytes,
  }) = SessionEvent_Progress;

  /// The session failed with a human-readable reason.
  const factory SessionEvent.failed({
    required String reason,
  }) = SessionEvent_Failed;
}

/// Mirror of `localsend_core::SessionSummary` (session index snapshot
/// entry).
class SessionSummary {
  final String id;
  final SessionDirection direction;
  final NodeDevice peer;
  final int fileCount;
  final MissionState state;

  /// True when this session's traffic is tunneled through the
  /// configured TURN relay.
  final bool viaRelay;

  /// Connection path label: "local" | "turn" ("stun" reserved).
  final String route;

  /// Per-file metadata and state, sorted by file name. Live byte
  /// counters are not included; subscribe to the per-session event
  /// stream for those.
  final List<MissionFileInfo> files;

  const SessionSummary({
    required this.id,
    required this.direction,
    required this.peer,
    required this.fileCount,
    required this.state,
    required this.viaRelay,
    required this.route,
    required this.files,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      direction.hashCode ^
      peer.hashCode ^
      fileCount.hashCode ^
      state.hashCode ^
      viaRelay.hashCode ^
      route.hashCode ^
      files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          direction == other.direction &&
          peer == other.peer &&
          fileCount == other.fileCount &&
          state == other.state &&
          viaRelay == other.viaRelay &&
          route == other.route &&
          files == other.files;
}
